#services:
 # kartverket:
  #  image: ${DOCKER_REGISTRY-}kartverket
   # build:
    #  context: .
     # dockerfile: Kartverket/Dockerfile
version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Gruppe13
      MYSQL_DATABASE: KartverketProject
      MYSQL_USER: root
      MYSQL_PASSWORD: Gruppe13
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  kartverket:
    image: ${DOCKER_REGISTRY-}kartverket
    build:
      context: .
      dockerfile: Kartverket/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=KartverketProject;User=root;Password=Gruppe13;"
    networks:
      - backend


volumes:
  mariadb_data:

networks:
  backend:    