// <auto-generated />
using System;
using Kartverket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kartverket.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241124183652_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kartverket.Data.Admin", b =>
                {
                    b.Property<int>("CaseWorkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CaseWorkerID"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CaseWorkerID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Kartverket.Data.Case", b =>
                {
                    b.Property<int>("CaseNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CaseNo"));

                    b.Property<string>("CommentCaseWorker")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("FylkesNo")
                        .HasColumnType("int");

                    b.Property<byte[]>("Images")
                        .HasColumnType("longblob");

                    b.Property<int>("Issue_IssueNr")
                        .HasColumnType("int");

                    b.Property<int>("KommuneNo")
                        .HasColumnType("int");

                    b.Property<string>("LocationInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusNo")
                        .HasColumnType("int");

                    b.Property<int>("User_UserID")
                        .HasColumnType("int");

                    b.HasKey("CaseNo");

                    b.ToTable("Case");
                });

            modelBuilder.Entity("Kartverket.Data.CaseWorker", b =>
                {
                    b.Property<int>("CaseWorkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CaseWorkerID"));

                    b.Property<int>("KartverketEmployee_EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CaseWorkerID");

                    b.ToTable("CaseWorkers");

                    b.HasData(
                        new
                        {
                            CaseWorkerID = 1,
                            KartverketEmployee_EmployeeID = 1,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 201,
                            KartverketEmployee_EmployeeID = 101,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 202,
                            KartverketEmployee_EmployeeID = 102,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 203,
                            KartverketEmployee_EmployeeID = 103,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 204,
                            KartverketEmployee_EmployeeID = 104,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 205,
                            KartverketEmployee_EmployeeID = 105,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 206,
                            KartverketEmployee_EmployeeID = 106,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 207,
                            KartverketEmployee_EmployeeID = 107,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 208,
                            KartverketEmployee_EmployeeID = 108,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 209,
                            KartverketEmployee_EmployeeID = 109,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 210,
                            KartverketEmployee_EmployeeID = 110,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 211,
                            KartverketEmployee_EmployeeID = 111,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 212,
                            KartverketEmployee_EmployeeID = 112,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 213,
                            KartverketEmployee_EmployeeID = 113,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 214,
                            KartverketEmployee_EmployeeID = 114,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 215,
                            KartverketEmployee_EmployeeID = 115,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 216,
                            KartverketEmployee_EmployeeID = 116,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 217,
                            KartverketEmployee_EmployeeID = 117,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 218,
                            KartverketEmployee_EmployeeID = 118,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 219,
                            KartverketEmployee_EmployeeID = 119,
                            MustChangePassword = false,
                            Password = "default"
                        },
                        new
                        {
                            CaseWorkerID = 220,
                            KartverketEmployee_EmployeeID = 120,
                            MustChangePassword = false,
                            Password = "default"
                        });
                });

            modelBuilder.Entity("Kartverket.Data.CaseWorkerAssignment", b =>
                {
                    b.Property<int>("CaseNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CaseNo"));

                    b.Property<int>("CaseWorkerID")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidHours")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CaseNo");

                    b.ToTable("CaseWorkerAssignment");
                });

            modelBuilder.Entity("Kartverket.Data.CaseWorkerList", b =>
                {
                    b.Property<int>("Case_CaseNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Case_CaseNo"));

                    b.Property<string>("AmountWorkers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CaseWorkerOverview_CaseWorkerID")
                        .HasColumnType("int");

                    b.HasKey("Case_CaseNo");

                    b.ToTable("CaseWorkerLists");
                });

            modelBuilder.Entity("Kartverket.Data.CaseWorkerOverview", b =>
                {
                    b.Property<int>("CaseWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CaseWorkerId"));

                    b.Property<int>("CaseWorkerList_Case_CaseNo")
                        .HasColumnType("int");

                    b.Property<string>("PaidHours")
                        .HasColumnType("longtext");

                    b.HasKey("CaseWorkerId");

                    b.ToTable("CaseWorkerOverviews");
                });

            modelBuilder.Entity("Kartverket.Data.FylkesInfo", b =>
                {
                    b.Property<int>("FylkesNameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FylkesNameID"));

                    b.Property<string>("FylkesName")
                        .HasColumnType("longtext");

                    b.HasKey("FylkesNameID");

                    b.ToTable("FylkesInfo");

                    b.HasData(
                        new
                        {
                            FylkesNameID = 3,
                            FylkesName = "Oslo"
                        },
                        new
                        {
                            FylkesNameID = 100,
                            FylkesName = "Sjø uten fylke"
                        },
                        new
                        {
                            FylkesNameID = 11,
                            FylkesName = "Rogaland"
                        },
                        new
                        {
                            FylkesNameID = 15,
                            FylkesName = "Møre og Romsdal"
                        },
                        new
                        {
                            FylkesNameID = 18,
                            FylkesName = "Nordland - Nordlánnda"
                        },
                        new
                        {
                            FylkesNameID = 31,
                            FylkesName = "Østfold"
                        },
                        new
                        {
                            FylkesNameID = 32,
                            FylkesName = "Akershus"
                        },
                        new
                        {
                            FylkesNameID = 33,
                            FylkesName = "Buskerud"
                        },
                        new
                        {
                            FylkesNameID = 34,
                            FylkesName = "Innlandet"
                        },
                        new
                        {
                            FylkesNameID = 39,
                            FylkesName = "Vestfold"
                        },
                        new
                        {
                            FylkesNameID = 40,
                            FylkesName = "Telemark"
                        },
                        new
                        {
                            FylkesNameID = 42,
                            FylkesName = "Agder"
                        },
                        new
                        {
                            FylkesNameID = 46,
                            FylkesName = "Vestland"
                        },
                        new
                        {
                            FylkesNameID = 50,
                            FylkesName = "Trøndelag - Trööndelage"
                        },
                        new
                        {
                            FylkesNameID = 55,
                            FylkesName = "Troms - Romsa - Tromssa"
                        },
                        new
                        {
                            FylkesNameID = 56,
                            FylkesName = "Finnmark - Finnmárku - Finmarkku"
                        });
                });

            modelBuilder.Entity("Kartverket.Data.Issue", b =>
                {
                    b.Property<int>("issueNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("issueNo"));

                    b.Property<string>("IssueType")
                        .HasColumnType("longtext");

                    b.HasKey("issueNo");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            issueNo = 1,
                            IssueType = "Adresse/Tomt"
                        },
                        new
                        {
                            issueNo = 2,
                            IssueType = "Vei/Sti"
                        },
                        new
                        {
                            issueNo = 3,
                            IssueType = "Sjø"
                        },
                        new
                        {
                            issueNo = 4,
                            IssueType = "Annet"
                        });
                });

            modelBuilder.Entity("Kartverket.Data.KartverketEmployee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Wage")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.ToTable("KartverketEmployee");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Firstname = "Admin",
                            Lastname = "Adminsen",
                            Mail = "admin@kartverket.no",
                            PhoneNo = 0,
                            Title = "Admin",
                            Wage = 0
                        },
                        new
                        {
                            EmployeeID = 101,
                            Firstname = "Erik",
                            Lastname = "Hansen",
                            Mail = "erik.hansen@kartverket.no",
                            PhoneNo = 12345678,
                            Title = "SeniorSurveyor",
                            Wage = 650000
                        },
                        new
                        {
                            EmployeeID = 102,
                            Firstname = "Maria",
                            Lastname = "Olsen",
                            Mail = "maria.olsen@kartverket.no",
                            PhoneNo = 23456789,
                            Title = "GIS Specialist",
                            Wage = 600000
                        },
                        new
                        {
                            EmployeeID = 103,
                            Firstname = "Anders",
                            Lastname = "Berg",
                            Mail = "anders.berg@kartverket.no",
                            PhoneNo = 34567890,
                            Title = "Property Lawyer",
                            Wage = 700000
                        },
                        new
                        {
                            EmployeeID = 104,
                            Firstname = "Sofia",
                            Lastname = "Larsen",
                            Mail = "sofia.larsen@kartverket.no",
                            PhoneNo = 45678901,
                            Title = "Cartographer",
                            Wage = 580000
                        },
                        new
                        {
                            EmployeeID = 105,
                            Firstname = "Nils",
                            Lastname = "Bakken",
                            Mail = "nils.bakken@kartverket.no",
                            PhoneNo = 56789012,
                            Title = "Data Analyst",
                            Wage = 620000
                        },
                        new
                        {
                            EmployeeID = 106,
                            Firstname = "Line",
                            Lastname = "Pedersen",
                            Mail = "line.pedersen@kartverket.no",
                            PhoneNo = 67890123,
                            Title = "GIS Manager",
                            Wage = 680000
                        },
                        new
                        {
                            EmployeeID = 107,
                            Firstname = "Jonas",
                            Lastname = "Andreassen",
                            Mail = "jonas.andreassen@kartverket.no",
                            PhoneNo = 78961234,
                            Title = "Senior Surveyor",
                            Wage = 660000
                        },
                        new
                        {
                            EmployeeID = 108,
                            Firstname = "Emma",
                            Lastname = "Kristiansen",
                            Mail = "emma.kristiansen@kartverket.no",
                            PhoneNo = 89012345,
                            Title = "Cartography Specialist",
                            Wage = 590000
                        },
                        new
                        {
                            EmployeeID = 109,
                            Firstname = "Martin",
                            Lastname = "Johansen",
                            Mail = "martin.johansen@kartverket.no",
                            PhoneNo = 90123456,
                            Title = "Data Analyst",
                            Wage = 610000
                        },
                        new
                        {
                            EmployeeID = 110,
                            Firstname = "Ingrid",
                            Lastname = "Nelson",
                            Mail = "ingrid.nelson@kartverket.no",
                            PhoneNo = 1234567,
                            Title = "Project Coordinator",
                            Wage = 630000
                        },
                        new
                        {
                            EmployeeID = 111,
                            Firstname = "Magnus",
                            Lastname = "Olsen",
                            Mail = "magnus.olsen@kartverket.no",
                            PhoneNo = 12345478,
                            Title = "Remote SensingExpert",
                            Wage = 670000
                        },
                        new
                        {
                            EmployeeID = 112,
                            Firstname = "Sara",
                            Lastname = "Hansen",
                            Mail = "sara.hansen@kartverket.no",
                            PhoneNo = 23459789,
                            Title = "Legal Advisor",
                            Wage = 690000
                        },
                        new
                        {
                            EmployeeID = 113,
                            Firstname = "Daniel",
                            Lastname = "Berg",
                            Mail = "daniel.berg@kartverket.no",
                            PhoneNo = 34517890,
                            Title = "Technical Specialist",
                            Wage = 640000
                        },
                        new
                        {
                            EmployeeID = 114,
                            Firstname = "Julia",
                            Lastname = "Larsen",
                            Mail = "julia.larsen@kartverket.no",
                            PhoneNo = 45671901,
                            Title = "Research Coordinator",
                            Wage = 620000
                        },
                        new
                        {
                            EmployeeID = 115,
                            Firstname = "Thomas",
                            Lastname = "Jensen",
                            Mail = "thomas.jensen@kartverket.no",
                            PhoneNo = 56779012,
                            Title = "Senior Analyst",
                            Wage = 650000
                        },
                        new
                        {
                            EmployeeID = 116,
                            Firstname = "Maria",
                            Lastname = "Andersen",
                            Mail = "maria.andersen@kartverket.no",
                            PhoneNo = 67820123,
                            Title = "Geospatial Specialist",
                            Wage = 600000
                        },
                        new
                        {
                            EmployeeID = 117,
                            Firstname = "Alexander",
                            Lastname = "Pedersen",
                            Mail = "alexander.pedersen@kartverket.no",
                            PhoneNo = 78901234,
                            Title = "Field Operations Manager",
                            Wage = 680000
                        },
                        new
                        {
                            EmployeeID = 118,
                            Firstname = "Sofia",
                            Lastname = "Olsen",
                            Mail = "sofia.olsen@kartverket.no",
                            PhoneNo = 83012345,
                            Title = "Data Visualization Expert",
                            Wage = 610000
                        },
                        new
                        {
                            EmployeeID = 119,
                            Firstname = "Hans",
                            Lastname = "Hansen",
                            Mail = "hans.hansen@kartverket.no",
                            PhoneNo = 90323436,
                            Title = "Senior Consultant",
                            Wage = 670000
                        },
                        new
                        {
                            EmployeeID = 120,
                            Firstname = "Linnea",
                            Lastname = "Berg",
                            Mail = "linnea.berg@kartverket.no",
                            PhoneNo = 1234267,
                            Title = "Research Analyst",
                            Wage = 590000
                        });
                });

            modelBuilder.Entity("Kartverket.Data.KommuneInfo", b =>
                {
                    b.Property<int>("KommuneInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KommuneInfoID"));

                    b.Property<string>("KommuneName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KommuneInfoID");

                    b.ToTable("KommuneInfo");

                    b.HasData(
                        new
                        {
                            KommuneInfoID = 5636,
                            KommuneName = "Unjárga - Nesseby"
                        },
                        new
                        {
                            KommuneInfoID = 100100,
                            KommuneName = "Sjø uten kommune"
                        },
                        new
                        {
                            KommuneInfoID = 5634,
                            KommuneName = "Vardø"
                        },
                        new
                        {
                            KommuneInfoID = 5632,
                            KommuneName = "Båtsfjord"
                        },
                        new
                        {
                            KommuneInfoID = 5630,
                            KommuneName = "Berlevåg"
                        },
                        new
                        {
                            KommuneInfoID = 5628,
                            KommuneName = "Deatnu - Tana"
                        },
                        new
                        {
                            KommuneInfoID = 5626,
                            KommuneName = "Gamvik"
                        },
                        new
                        {
                            KommuneInfoID = 5624,
                            KommuneName = "Lebesby"
                        },
                        new
                        {
                            KommuneInfoID = 5622,
                            KommuneName = "Porsanger - Porsáŋgu - Porsanki"
                        },
                        new
                        {
                            KommuneInfoID = 5620,
                            KommuneName = "Nordkapp"
                        },
                        new
                        {
                            KommuneInfoID = 5618,
                            KommuneName = "Måsøy"
                        },
                        new
                        {
                            KommuneInfoID = 5616,
                            KommuneName = "Hasvik"
                        },
                        new
                        {
                            KommuneInfoID = 5614,
                            KommuneName = "Loppa"
                        },
                        new
                        {
                            KommuneInfoID = 5612,
                            KommuneName = "Guovdageaidnu - Kautokeino"
                        },
                        new
                        {
                            KommuneInfoID = 5610,
                            KommuneName = "Kárášjohka - Karasjok"
                        },
                        new
                        {
                            KommuneInfoID = 5607,
                            KommuneName = "Vadsø"
                        },
                        new
                        {
                            KommuneInfoID = 5605,
                            KommuneName = "Sør - Varanger"
                        },
                        new
                        {
                            KommuneInfoID = 5603,
                            KommuneName = "Hammerfest - Hámmerfeasta"
                        },
                        new
                        {
                            KommuneInfoID = 5601,
                            KommuneName = "Alta"
                        },
                        new
                        {
                            KommuneInfoID = 5546,
                            KommuneName = "Kvænangen"
                        },
                        new
                        {
                            KommuneInfoID = 5544,
                            KommuneName = "Nordreisa - Ráisa - Raisi"
                        },
                        new
                        {
                            KommuneInfoID = 5542,
                            KommuneName = "Skjervøy"
                        },
                        new
                        {
                            KommuneInfoID = 5540,
                            KommuneName = "Gáivuotna - Kåfjord - Kaivuono"
                        },
                        new
                        {
                            KommuneInfoID = 5538,
                            KommuneName = "Storfjord - Omasvuotna - Omasvuono"
                        },
                        new
                        {
                            KommuneInfoID = 5536,
                            KommuneName = "Lyngen"
                        },
                        new
                        {
                            KommuneInfoID = 5534,
                            KommuneName = "Karlsøy"
                        },
                        new
                        {
                            KommuneInfoID = 5532,
                            KommuneName = "Balsfjord"
                        },
                        new
                        {
                            KommuneInfoID = 5530,
                            KommuneName = "Senja"
                        },
                        new
                        {
                            KommuneInfoID = 5528,
                            KommuneName = "Dyrøy"
                        },
                        new
                        {
                            KommuneInfoID = 5526,
                            KommuneName = "Sørreisa"
                        },
                        new
                        {
                            KommuneInfoID = 5524,
                            KommuneName = "Målselv"
                        },
                        new
                        {
                            KommuneInfoID = 5522,
                            KommuneName = "Salangen"
                        },
                        new
                        {
                            KommuneInfoID = 5520,
                            KommuneName = "Bardu"
                        },
                        new
                        {
                            KommuneInfoID = 5518,
                            KommuneName = "Loabák - Lavangen"
                        },
                        new
                        {
                            KommuneInfoID = 5516,
                            KommuneName = "Gratangen"
                        },
                        new
                        {
                            KommuneInfoID = 5514,
                            KommuneName = "Ibestad"
                        },
                        new
                        {
                            KommuneInfoID = 5512,
                            KommuneName = "Tjeldsund - Dielddanuorri"
                        },
                        new
                        {
                            KommuneInfoID = 5510,
                            KommuneName = "Kvæfjord"
                        },
                        new
                        {
                            KommuneInfoID = 5503,
                            KommuneName = "Harstad - Hárstták"
                        },
                        new
                        {
                            KommuneInfoID = 5501,
                            KommuneName = "Tromsø"
                        },
                        new
                        {
                            KommuneInfoID = 5061,
                            KommuneName = "Rindal"
                        },
                        new
                        {
                            KommuneInfoID = 5060,
                            KommuneName = "Nærøysund"
                        },
                        new
                        {
                            KommuneInfoID = 5059,
                            KommuneName = "Orkland"
                        },
                        new
                        {
                            KommuneInfoID = 5058,
                            KommuneName = "Åfjord"
                        },
                        new
                        {
                            KommuneInfoID = 5057,
                            KommuneName = "Ørland"
                        },
                        new
                        {
                            KommuneInfoID = 5056,
                            KommuneName = "Hitra"
                        },
                        new
                        {
                            KommuneInfoID = 5055,
                            KommuneName = "Heim"
                        },
                        new
                        {
                            KommuneInfoID = 5054,
                            KommuneName = "IndreFosen"
                        },
                        new
                        {
                            KommuneInfoID = 5053,
                            KommuneName = "Inderøy"
                        },
                        new
                        {
                            KommuneInfoID = 5052,
                            KommuneName = "Leka"
                        },
                        new
                        {
                            KommuneInfoID = 5049,
                            KommuneName = "Flatanger"
                        },
                        new
                        {
                            KommuneInfoID = 5047,
                            KommuneName = "Overhalla"
                        },
                        new
                        {
                            KommuneInfoID = 5046,
                            KommuneName = "Høylandet"
                        },
                        new
                        {
                            KommuneInfoID = 5045,
                            KommuneName = "Grong"
                        },
                        new
                        {
                            KommuneInfoID = 5044,
                            KommuneName = "Namsskogan"
                        },
                        new
                        {
                            KommuneInfoID = 5043,
                            KommuneName = "Raarvihke - Røyrvik"
                        },
                        new
                        {
                            KommuneInfoID = 5042,
                            KommuneName = "Lierne"
                        },
                        new
                        {
                            KommuneInfoID = 5041,
                            KommuneName = "Snåase - Snåsa"
                        },
                        new
                        {
                            KommuneInfoID = 5038,
                            KommuneName = "Verdal"
                        },
                        new
                        {
                            KommuneInfoID = 5037,
                            KommuneName = "Levanger"
                        },
                        new
                        {
                            KommuneInfoID = 5036,
                            KommuneName = "Frosta"
                        },
                        new
                        {
                            KommuneInfoID = 5035,
                            KommuneName = "Stjørdal"
                        },
                        new
                        {
                            KommuneInfoID = 5034,
                            KommuneName = "Meråker"
                        },
                        new
                        {
                            KommuneInfoID = 5033,
                            KommuneName = "Tydal"
                        },
                        new
                        {
                            KommuneInfoID = 5032,
                            KommuneName = "Selbu"
                        },
                        new
                        {
                            KommuneInfoID = 5031,
                            KommuneName = "Malvik"
                        },
                        new
                        {
                            KommuneInfoID = 5029,
                            KommuneName = "Skaun"
                        },
                        new
                        {
                            KommuneInfoID = 5028,
                            KommuneName = "Melhus"
                        },
                        new
                        {
                            KommuneInfoID = 5027,
                            KommuneName = "MidtreGauldal"
                        },
                        new
                        {
                            KommuneInfoID = 5026,
                            KommuneName = "Holtålen"
                        },
                        new
                        {
                            KommuneInfoID = 5025,
                            KommuneName = "Rosse - Røros"
                        },
                        new
                        {
                            KommuneInfoID = 5022,
                            KommuneName = "Rennebu"
                        },
                        new
                        {
                            KommuneInfoID = 5021,
                            KommuneName = "Oppdal"
                        },
                        new
                        {
                            KommuneInfoID = 5020,
                            KommuneName = "Osen"
                        },
                        new
                        {
                            KommuneInfoID = 5014,
                            KommuneName = "Frøya"
                        },
                        new
                        {
                            KommuneInfoID = 5007,
                            KommuneName = "Namsos - Nåavmesjenjaelmie"
                        },
                        new
                        {
                            KommuneInfoID = 5006,
                            KommuneName = "Steinkjer"
                        },
                        new
                        {
                            KommuneInfoID = 5001,
                            KommuneName = "Trondheim - Tråante"
                        },
                        new
                        {
                            KommuneInfoID = 4651,
                            KommuneName = "Stryn"
                        },
                        new
                        {
                            KommuneInfoID = 4650,
                            KommuneName = "Gloppen"
                        },
                        new
                        {
                            KommuneInfoID = 4649,
                            KommuneName = "Stad"
                        },
                        new
                        {
                            KommuneInfoID = 4648,
                            KommuneName = "Bremanger"
                        },
                        new
                        {
                            KommuneInfoID = 4647,
                            KommuneName = "Sunnfjord"
                        },
                        new
                        {
                            KommuneInfoID = 4646,
                            KommuneName = "Fjaler"
                        },
                        new
                        {
                            KommuneInfoID = 4645,
                            KommuneName = "Askvoll"
                        },
                        new
                        {
                            KommuneInfoID = 4644,
                            KommuneName = "Luster"
                        },
                        new
                        {
                            KommuneInfoID = 4643,
                            KommuneName = "Årdal"
                        },
                        new
                        {
                            KommuneInfoID = 4642,
                            KommuneName = "Lærdal"
                        },
                        new
                        {
                            KommuneInfoID = 4641,
                            KommuneName = "Aurland"
                        },
                        new
                        {
                            KommuneInfoID = 4640,
                            KommuneName = "Sogndal"
                        },
                        new
                        {
                            KommuneInfoID = 4639,
                            KommuneName = "Vik"
                        },
                        new
                        {
                            KommuneInfoID = 4638,
                            KommuneName = "Høyanger"
                        },
                        new
                        {
                            KommuneInfoID = 4637,
                            KommuneName = "Hyllestad"
                        },
                        new
                        {
                            KommuneInfoID = 4636,
                            KommuneName = "Solund"
                        },
                        new
                        {
                            KommuneInfoID = 4635,
                            KommuneName = "Gulen"
                        },
                        new
                        {
                            KommuneInfoID = 4634,
                            KommuneName = "Masfjorden"
                        },
                        new
                        {
                            KommuneInfoID = 4633,
                            KommuneName = "Fedje"
                        },
                        new
                        {
                            KommuneInfoID = 4632,
                            KommuneName = "Austrheim"
                        },
                        new
                        {
                            KommuneInfoID = 4631,
                            KommuneName = "Alver"
                        },
                        new
                        {
                            KommuneInfoID = 4630,
                            KommuneName = "Osterøy"
                        },
                        new
                        {
                            KommuneInfoID = 4629,
                            KommuneName = "Modalen"
                        },
                        new
                        {
                            KommuneInfoID = 4628,
                            KommuneName = "Vaksdal"
                        },
                        new
                        {
                            KommuneInfoID = 4627,
                            KommuneName = "Askøy"
                        },
                        new
                        {
                            KommuneInfoID = 4626,
                            KommuneName = "Øygarden"
                        },
                        new
                        {
                            KommuneInfoID = 4625,
                            KommuneName = "Austevoll"
                        },
                        new
                        {
                            KommuneInfoID = 4624,
                            KommuneName = "Bjørnafjorden"
                        },
                        new
                        {
                            KommuneInfoID = 4623,
                            KommuneName = "Samnanger"
                        },
                        new
                        {
                            KommuneInfoID = 4622,
                            KommuneName = "Kvam"
                        },
                        new
                        {
                            KommuneInfoID = 4621,
                            KommuneName = "Voss"
                        },
                        new
                        {
                            KommuneInfoID = 4620,
                            KommuneName = "Ulvik"
                        },
                        new
                        {
                            KommuneInfoID = 4619,
                            KommuneName = "Eidfjord"
                        },
                        new
                        {
                            KommuneInfoID = 4618,
                            KommuneName = "Ullensvang"
                        },
                        new
                        {
                            KommuneInfoID = 4617,
                            KommuneName = "Kvinnherad"
                        },
                        new
                        {
                            KommuneInfoID = 4616,
                            KommuneName = "Tysnes"
                        },
                        new
                        {
                            KommuneInfoID = 4615,
                            KommuneName = "Fitjar"
                        },
                        new
                        {
                            KommuneInfoID = 4614,
                            KommuneName = "Stord"
                        },
                        new
                        {
                            KommuneInfoID = 4613,
                            KommuneName = "Bømlo"
                        },
                        new
                        {
                            KommuneInfoID = 4612,
                            KommuneName = "Sveio"
                        },
                        new
                        {
                            KommuneInfoID = 4611,
                            KommuneName = "Etne"
                        },
                        new
                        {
                            KommuneInfoID = 4602,
                            KommuneName = "Kinn"
                        },
                        new
                        {
                            KommuneInfoID = 4601,
                            KommuneName = "Bergen"
                        },
                        new
                        {
                            KommuneInfoID = 4228,
                            KommuneName = "Sirdal"
                        },
                        new
                        {
                            KommuneInfoID = 4227,
                            KommuneName = "Kvinesdal"
                        },
                        new
                        {
                            KommuneInfoID = 4226,
                            KommuneName = "Hægebostad"
                        },
                        new
                        {
                            KommuneInfoID = 4225,
                            KommuneName = "Lyngdal"
                        },
                        new
                        {
                            KommuneInfoID = 4224,
                            KommuneName = "Åseral"
                        },
                        new
                        {
                            KommuneInfoID = 4223,
                            KommuneName = "Vennesla"
                        },
                        new
                        {
                            KommuneInfoID = 4222,
                            KommuneName = "Bykle"
                        },
                        new
                        {
                            KommuneInfoID = 4221,
                            KommuneName = "Valle"
                        },
                        new
                        {
                            KommuneInfoID = 4220,
                            KommuneName = "Bygland"
                        },
                        new
                        {
                            KommuneInfoID = 4219,
                            KommuneName = "EvjeogHornnes"
                        },
                        new
                        {
                            KommuneInfoID = 4218,
                            KommuneName = "Iveland"
                        },
                        new
                        {
                            KommuneInfoID = 4217,
                            KommuneName = "Åmli"
                        },
                        new
                        {
                            KommuneInfoID = 4216,
                            KommuneName = "Birkenes"
                        },
                        new
                        {
                            KommuneInfoID = 4215,
                            KommuneName = "Lillesand"
                        },
                        new
                        {
                            KommuneInfoID = 4214,
                            KommuneName = "Froland"
                        },
                        new
                        {
                            KommuneInfoID = 4213,
                            KommuneName = "Tvedestrand"
                        },
                        new
                        {
                            KommuneInfoID = 4212,
                            KommuneName = "Vegårshei"
                        },
                        new
                        {
                            KommuneInfoID = 4211,
                            KommuneName = "Gjerstad"
                        },
                        new
                        {
                            KommuneInfoID = 4207,
                            KommuneName = "Flekkefjord"
                        },
                        new
                        {
                            KommuneInfoID = 4206,
                            KommuneName = "Farsund"
                        },
                        new
                        {
                            KommuneInfoID = 4205,
                            KommuneName = "Lindesnes"
                        },
                        new
                        {
                            KommuneInfoID = 4204,
                            KommuneName = "Kristiansand"
                        },
                        new
                        {
                            KommuneInfoID = 4203,
                            KommuneName = "Arendal"
                        },
                        new
                        {
                            KommuneInfoID = 4202,
                            KommuneName = "Grimstad"
                        },
                        new
                        {
                            KommuneInfoID = 4201,
                            KommuneName = "Risør"
                        },
                        new
                        {
                            KommuneInfoID = 4036,
                            KommuneName = "Vinje"
                        },
                        new
                        {
                            KommuneInfoID = 4034,
                            KommuneName = "Tokke"
                        },
                        new
                        {
                            KommuneInfoID = 4032,
                            KommuneName = "Fyresdal"
                        },
                        new
                        {
                            KommuneInfoID = 4030,
                            KommuneName = "Nissedal"
                        },
                        new
                        {
                            KommuneInfoID = 4028,
                            KommuneName = "Kviteseid"
                        },
                        new
                        {
                            KommuneInfoID = 4026,
                            KommuneName = "Tinn"
                        },
                        new
                        {
                            KommuneInfoID = 4024,
                            KommuneName = "Hjartdal"
                        },
                        new
                        {
                            KommuneInfoID = 4022,
                            KommuneName = "Seljord"
                        },
                        new
                        {
                            KommuneInfoID = 4020,
                            KommuneName = "Midt - Telemark"
                        },
                        new
                        {
                            KommuneInfoID = 4018,
                            KommuneName = "Nome"
                        },
                        new
                        {
                            KommuneInfoID = 4016,
                            KommuneName = "Drangedal"
                        },
                        new
                        {
                            KommuneInfoID = 4014,
                            KommuneName = "Kragerø"
                        },
                        new
                        {
                            KommuneInfoID = 4012,
                            KommuneName = "Bamble"
                        },
                        new
                        {
                            KommuneInfoID = 4010,
                            KommuneName = "Siljan"
                        },
                        new
                        {
                            KommuneInfoID = 4005,
                            KommuneName = "Notodden"
                        },
                        new
                        {
                            KommuneInfoID = 4003,
                            KommuneName = "Skien"
                        },
                        new
                        {
                            KommuneInfoID = 4001,
                            KommuneName = "Porsgrunn"
                        },
                        new
                        {
                            KommuneInfoID = 3911,
                            KommuneName = "Færder"
                        },
                        new
                        {
                            KommuneInfoID = 3909,
                            KommuneName = "Larvik"
                        },
                        new
                        {
                            KommuneInfoID = 3907,
                            KommuneName = "Sandefjord"
                        },
                        new
                        {
                            KommuneInfoID = 3905,
                            KommuneName = "Tønsberg"
                        },
                        new
                        {
                            KommuneInfoID = 3903,
                            KommuneName = "Holmestrand"
                        },
                        new
                        {
                            KommuneInfoID = 3901,
                            KommuneName = "Horten"
                        },
                        new
                        {
                            KommuneInfoID = 3454,
                            KommuneName = "Vang"
                        },
                        new
                        {
                            KommuneInfoID = 3453,
                            KommuneName = "ØystreSlidre"
                        },
                        new
                        {
                            KommuneInfoID = 3452,
                            KommuneName = "VestreSlidre"
                        },
                        new
                        {
                            KommuneInfoID = 3451,
                            KommuneName = "Nord - Aurdal"
                        },
                        new
                        {
                            KommuneInfoID = 3450,
                            KommuneName = "Etnedal"
                        },
                        new
                        {
                            KommuneInfoID = 3449,
                            KommuneName = "Sør - Aurdal"
                        },
                        new
                        {
                            KommuneInfoID = 3448,
                            KommuneName = "NordreLand"
                        },
                        new
                        {
                            KommuneInfoID = 3447,
                            KommuneName = "SøndreLand"
                        },
                        new
                        {
                            KommuneInfoID = 3446,
                            KommuneName = "Gran"
                        },
                        new
                        {
                            KommuneInfoID = 3443,
                            KommuneName = "VestreToten"
                        },
                        new
                        {
                            KommuneInfoID = 3442,
                            KommuneName = "ØstreToten"
                        },
                        new
                        {
                            KommuneInfoID = 3441,
                            KommuneName = "Gausdal"
                        },
                        new
                        {
                            KommuneInfoID = 3440,
                            KommuneName = "Øyer"
                        },
                        new
                        {
                            KommuneInfoID = 3439,
                            KommuneName = "Ringebu"
                        },
                        new
                        {
                            KommuneInfoID = 3438,
                            KommuneName = "Sør - Fron"
                        },
                        new
                        {
                            KommuneInfoID = 3437,
                            KommuneName = "Sel"
                        },
                        new
                        {
                            KommuneInfoID = 3436,
                            KommuneName = "Nord - Fron"
                        },
                        new
                        {
                            KommuneInfoID = 3435,
                            KommuneName = "Vågå"
                        },
                        new
                        {
                            KommuneInfoID = 3434,
                            KommuneName = "Lom"
                        },
                        new
                        {
                            KommuneInfoID = 3433,
                            KommuneName = "Skjåk"
                        },
                        new
                        {
                            KommuneInfoID = 3432,
                            KommuneName = "Lesja"
                        },
                        new
                        {
                            KommuneInfoID = 3431,
                            KommuneName = "Dovre"
                        },
                        new
                        {
                            KommuneInfoID = 3430,
                            KommuneName = "Os"
                        },
                        new
                        {
                            KommuneInfoID = 3429,
                            KommuneName = "Folldal"
                        },
                        new
                        {
                            KommuneInfoID = 3428,
                            KommuneName = "Alvdal"
                        },
                        new
                        {
                            KommuneInfoID = 3427,
                            KommuneName = "Tynset"
                        },
                        new
                        {
                            KommuneInfoID = 3426,
                            KommuneName = "Tolga"
                        },
                        new
                        {
                            KommuneInfoID = 3425,
                            KommuneName = "Engerdal"
                        },
                        new
                        {
                            KommuneInfoID = 3424,
                            KommuneName = "Rendalen"
                        },
                        new
                        {
                            KommuneInfoID = 3423,
                            KommuneName = "Stor - Elvdal"
                        },
                        new
                        {
                            KommuneInfoID = 3422,
                            KommuneName = "Åmot"
                        },
                        new
                        {
                            KommuneInfoID = 3421,
                            KommuneName = "Trysil"
                        },
                        new
                        {
                            KommuneInfoID = 3420,
                            KommuneName = "Elverum"
                        },
                        new
                        {
                            KommuneInfoID = 3419,
                            KommuneName = "Våler"
                        },
                        new
                        {
                            KommuneInfoID = 3418,
                            KommuneName = "Åsnes"
                        },
                        new
                        {
                            KommuneInfoID = 3417,
                            KommuneName = "Grue"
                        },
                        new
                        {
                            KommuneInfoID = 3416,
                            KommuneName = "Eidskog"
                        },
                        new
                        {
                            KommuneInfoID = 3415,
                            KommuneName = "Sør - Odal"
                        },
                        new
                        {
                            KommuneInfoID = 3414,
                            KommuneName = "Nord - Odal"
                        },
                        new
                        {
                            KommuneInfoID = 3413,
                            KommuneName = "Stange"
                        },
                        new
                        {
                            KommuneInfoID = 3412,
                            KommuneName = "Løten"
                        },
                        new
                        {
                            KommuneInfoID = 3411,
                            KommuneName = "Ringsaker"
                        },
                        new
                        {
                            KommuneInfoID = 3407,
                            KommuneName = "Gjøvik"
                        },
                        new
                        {
                            KommuneInfoID = 3405,
                            KommuneName = "Lillehammer"
                        },
                        new
                        {
                            KommuneInfoID = 3403,
                            KommuneName = "Hamar"
                        },
                        new
                        {
                            KommuneInfoID = 3401,
                            KommuneName = "Kongsvinger"
                        },
                        new
                        {
                            KommuneInfoID = 3338,
                            KommuneName = "NoreogUvdal"
                        },
                        new
                        {
                            KommuneInfoID = 3336,
                            KommuneName = "Rollag"
                        },
                        new
                        {
                            KommuneInfoID = 3334,
                            KommuneName = "Flesberg"
                        },
                        new
                        {
                            KommuneInfoID = 3332,
                            KommuneName = "Sigdal"
                        },
                        new
                        {
                            KommuneInfoID = 3330,
                            KommuneName = "Hol"
                        },
                        new
                        {
                            KommuneInfoID = 3328,
                            KommuneName = "Ål"
                        },
                        new
                        {
                            KommuneInfoID = 3326,
                            KommuneName = "Hemsedal"
                        },
                        new
                        {
                            KommuneInfoID = 3324,
                            KommuneName = "Gol"
                        },
                        new
                        {
                            KommuneInfoID = 3322,
                            KommuneName = "Nesbyen"
                        },
                        new
                        {
                            KommuneInfoID = 3320,
                            KommuneName = "Flå"
                        },
                        new
                        {
                            KommuneInfoID = 3318,
                            KommuneName = "Krødsherad"
                        },
                        new
                        {
                            KommuneInfoID = 3316,
                            KommuneName = "Modum"
                        },
                        new
                        {
                            KommuneInfoID = 3314,
                            KommuneName = "ØvreEiker"
                        },
                        new
                        {
                            KommuneInfoID = 3312,
                            KommuneName = "Lier"
                        },
                        new
                        {
                            KommuneInfoID = 3310,
                            KommuneName = "Hole"
                        },
                        new
                        {
                            KommuneInfoID = 3305,
                            KommuneName = "Ringerike"
                        },
                        new
                        {
                            KommuneInfoID = 3303,
                            KommuneName = "Kongsberg"
                        },
                        new
                        {
                            KommuneInfoID = 3301,
                            KommuneName = "Drammen"
                        },
                        new
                        {
                            KommuneInfoID = 3242,
                            KommuneName = "Hurdal"
                        },
                        new
                        {
                            KommuneInfoID = 3240,
                            KommuneName = "Eidsvoll"
                        },
                        new
                        {
                            KommuneInfoID = 3238,
                            KommuneName = "Nannestad"
                        },
                        new
                        {
                            KommuneInfoID = 3236,
                            KommuneName = "Jevnaker"
                        },
                        new
                        {
                            KommuneInfoID = 3234,
                            KommuneName = "Lunner"
                        },
                        new
                        {
                            KommuneInfoID = 3232,
                            KommuneName = "Nittedal"
                        },
                        new
                        {
                            KommuneInfoID = 3230,
                            KommuneName = "Gjerdrum"
                        },
                        new
                        {
                            KommuneInfoID = 3228,
                            KommuneName = "Nes"
                        },
                        new
                        {
                            KommuneInfoID = 3226,
                            KommuneName = "Aurskog - Høland"
                        },
                        new
                        {
                            KommuneInfoID = 3224,
                            KommuneName = "Rælingen"
                        },
                        new
                        {
                            KommuneInfoID = 3222,
                            KommuneName = "Lørenskog"
                        },
                        new
                        {
                            KommuneInfoID = 3220,
                            KommuneName = "Enebakk"
                        },
                        new
                        {
                            KommuneInfoID = 3218,
                            KommuneName = "Ås"
                        },
                        new
                        {
                            KommuneInfoID = 3216,
                            KommuneName = "Vestby"
                        },
                        new
                        {
                            KommuneInfoID = 3214,
                            KommuneName = "Frogn"
                        },
                        new
                        {
                            KommuneInfoID = 3212,
                            KommuneName = "Nesodden"
                        },
                        new
                        {
                            KommuneInfoID = 3209,
                            KommuneName = "Ullensaker"
                        },
                        new
                        {
                            KommuneInfoID = 3207,
                            KommuneName = "NordreFollo"
                        },
                        new
                        {
                            KommuneInfoID = 3205,
                            KommuneName = "Lillestrøm"
                        },
                        new
                        {
                            KommuneInfoID = 3203,
                            KommuneName = "Asker"
                        },
                        new
                        {
                            KommuneInfoID = 3201,
                            KommuneName = "Bærum"
                        },
                        new
                        {
                            KommuneInfoID = 3124,
                            KommuneName = "Aremark"
                        },
                        new
                        {
                            KommuneInfoID = 3122,
                            KommuneName = "Marker"
                        },
                        new
                        {
                            KommuneInfoID = 3120,
                            KommuneName = "Rakkestad"
                        },
                        new
                        {
                            KommuneInfoID = 3118,
                            KommuneName = "IndreØstfold"
                        },
                        new
                        {
                            KommuneInfoID = 3116,
                            KommuneName = "Skiptvet"
                        },
                        new
                        {
                            KommuneInfoID = 3114,
                            KommuneName = "Våler"
                        },
                        new
                        {
                            KommuneInfoID = 3112,
                            KommuneName = "Råde"
                        },
                        new
                        {
                            KommuneInfoID = 3110,
                            KommuneName = "Hvaler"
                        },
                        new
                        {
                            KommuneInfoID = 3107,
                            KommuneName = "Fredrikstad"
                        },
                        new
                        {
                            KommuneInfoID = 3105,
                            KommuneName = "Sarpsborg"
                        },
                        new
                        {
                            KommuneInfoID = 3103,
                            KommuneName = "Moss"
                        },
                        new
                        {
                            KommuneInfoID = 3101,
                            KommuneName = "Halden"
                        },
                        new
                        {
                            KommuneInfoID = 1875,
                            KommuneName = "Hábmer - Hamarøy"
                        },
                        new
                        {
                            KommuneInfoID = 1874,
                            KommuneName = "Moskenes"
                        },
                        new
                        {
                            KommuneInfoID = 1871,
                            KommuneName = "Andøy"
                        },
                        new
                        {
                            KommuneInfoID = 1870,
                            KommuneName = "Sortland - Suortá"
                        },
                        new
                        {
                            KommuneInfoID = 1868,
                            KommuneName = "Øksnes"
                        },
                        new
                        {
                            KommuneInfoID = 1867,
                            KommuneName = "Bø"
                        },
                        new
                        {
                            KommuneInfoID = 1866,
                            KommuneName = "Hadsel"
                        },
                        new
                        {
                            KommuneInfoID = 1865,
                            KommuneName = "Vågan"
                        },
                        new
                        {
                            KommuneInfoID = 1860,
                            KommuneName = "Vestvågøy"
                        },
                        new
                        {
                            KommuneInfoID = 1859,
                            KommuneName = "Flakstad"
                        },
                        new
                        {
                            KommuneInfoID = 1857,
                            KommuneName = "Værøy"
                        },
                        new
                        {
                            KommuneInfoID = 1856,
                            KommuneName = "Røst"
                        },
                        new
                        {
                            KommuneInfoID = 1853,
                            KommuneName = "Evenes - Evenášši"
                        },
                        new
                        {
                            KommuneInfoID = 1851,
                            KommuneName = "Lødingen"
                        },
                        new
                        {
                            KommuneInfoID = 1848,
                            KommuneName = "Steigen"
                        },
                        new
                        {
                            KommuneInfoID = 1845,
                            KommuneName = "Sørfold"
                        },
                        new
                        {
                            KommuneInfoID = 1841,
                            KommuneName = "Fauske - Fuossko"
                        },
                        new
                        {
                            KommuneInfoID = 1840,
                            KommuneName = "Saltdal"
                        },
                        new
                        {
                            KommuneInfoID = 1839,
                            KommuneName = "Beiarn"
                        },
                        new
                        {
                            KommuneInfoID = 1838,
                            KommuneName = "Gildeskål"
                        },
                        new
                        {
                            KommuneInfoID = 1837,
                            KommuneName = "Meløy"
                        },
                        new
                        {
                            KommuneInfoID = 1836,
                            KommuneName = "Rødøy"
                        },
                        new
                        {
                            KommuneInfoID = 1835,
                            KommuneName = "Træna"
                        },
                        new
                        {
                            KommuneInfoID = 1834,
                            KommuneName = "Lurøy"
                        },
                        new
                        {
                            KommuneInfoID = 1833,
                            KommuneName = "Rana"
                        },
                        new
                        {
                            KommuneInfoID = 1832,
                            KommuneName = "Hemnes"
                        },
                        new
                        {
                            KommuneInfoID = 1828,
                            KommuneName = "Nesna"
                        },
                        new
                        {
                            KommuneInfoID = 1827,
                            KommuneName = "Dønna"
                        },
                        new
                        {
                            KommuneInfoID = 1826,
                            KommuneName = "Aarborte - Hattfjelldal"
                        },
                        new
                        {
                            KommuneInfoID = 1825,
                            KommuneName = "Grane"
                        },
                        new
                        {
                            KommuneInfoID = 1824,
                            KommuneName = "Vefsn"
                        },
                        new
                        {
                            KommuneInfoID = 1822,
                            KommuneName = "Leirfjord"
                        },
                        new
                        {
                            KommuneInfoID = 1820,
                            KommuneName = "Alstahaug"
                        },
                        new
                        {
                            KommuneInfoID = 1818,
                            KommuneName = "Herøy"
                        },
                        new
                        {
                            KommuneInfoID = 1816,
                            KommuneName = "Vevelstad"
                        },
                        new
                        {
                            KommuneInfoID = 1815,
                            KommuneName = "Vega"
                        },
                        new
                        {
                            KommuneInfoID = 1813,
                            KommuneName = "Brønnøy"
                        },
                        new
                        {
                            KommuneInfoID = 1812,
                            KommuneName = "Sømna"
                        },
                        new
                        {
                            KommuneInfoID = 1811,
                            KommuneName = "Bindal"
                        },
                        new
                        {
                            KommuneInfoID = 1806,
                            KommuneName = "Narvik"
                        },
                        new
                        {
                            KommuneInfoID = 1804,
                            KommuneName = "Bodø"
                        },
                        new
                        {
                            KommuneInfoID = 158,
                            KommuneName = "Hara"
                        },
                        new
                        {
                            KommuneInfoID = 1579,
                            KommuneName = "Hustadvika"
                        },
                        new
                        {
                            KommuneInfoID = 1578,
                            KommuneName = "Fjord"
                        },
                        new
                        {
                            KommuneInfoID = 1577,
                            KommuneName = "Volda"
                        },
                        new
                        {
                            KommuneInfoID = 1576,
                            KommuneName = "Aure"
                        },
                        new
                        {
                            KommuneInfoID = 1573,
                            KommuneName = "Smøla"
                        },
                        new
                        {
                            KommuneInfoID = 1566,
                            KommuneName = "Surnadal"
                        },
                        new
                        {
                            KommuneInfoID = 1563,
                            KommuneName = "Sunndal"
                        },
                        new
                        {
                            KommuneInfoID = 1560,
                            KommuneName = "Tingvoll"
                        },
                        new
                        {
                            KommuneInfoID = 1557,
                            KommuneName = "Gjemnes"
                        },
                        new
                        {
                            KommuneInfoID = 1554,
                            KommuneName = "Averøy"
                        },
                        new
                        {
                            KommuneInfoID = 1547,
                            KommuneName = "Aukra"
                        },
                        new
                        {
                            KommuneInfoID = 1539,
                            KommuneName = "Rauma"
                        },
                        new
                        {
                            KommuneInfoID = 1535,
                            KommuneName = "Vestnes"
                        },
                        new
                        {
                            KommuneInfoID = 1532,
                            KommuneName = "Giske"
                        },
                        new
                        {
                            KommuneInfoID = 1531,
                            KommuneName = "Sula"
                        },
                        new
                        {
                            KommuneInfoID = 1528,
                            KommuneName = "Sykkylven"
                        },
                        new
                        {
                            KommuneInfoID = 1525,
                            KommuneName = "Stranda"
                        },
                        new
                        {
                            KommuneInfoID = 1520,
                            KommuneName = "Ørsta"
                        },
                        new
                        {
                            KommuneInfoID = 1517,
                            KommuneName = "Hareid"
                        },
                        new
                        {
                            KommuneInfoID = 1516,
                            KommuneName = "Ulstein"
                        },
                        new
                        {
                            KommuneInfoID = 1515,
                            KommuneName = "Herøy"
                        },
                        new
                        {
                            KommuneInfoID = 1514,
                            KommuneName = "Sande"
                        },
                        new
                        {
                            KommuneInfoID = 1511,
                            KommuneName = "Vanylven"
                        },
                        new
                        {
                            KommuneInfoID = 1508,
                            KommuneName = "Ålesund"
                        },
                        new
                        {
                            KommuneInfoID = 1506,
                            KommuneName = "Molde"
                        },
                        new
                        {
                            KommuneInfoID = 1505,
                            KommuneName = "Kristiansund"
                        },
                        new
                        {
                            KommuneInfoID = 1160,
                            KommuneName = "Vindafjord"
                        },
                        new
                        {
                            KommuneInfoID = 1151,
                            KommuneName = "Utsira"
                        },
                        new
                        {
                            KommuneInfoID = 1149,
                            KommuneName = "Karmøy"
                        },
                        new
                        {
                            KommuneInfoID = 1146,
                            KommuneName = "Tysvær"
                        },
                        new
                        {
                            KommuneInfoID = 1145,
                            KommuneName = "Bokn"
                        },
                        new
                        {
                            KommuneInfoID = 1144,
                            KommuneName = "Kvitsøy"
                        },
                        new
                        {
                            KommuneInfoID = 1135,
                            KommuneName = "Sauda"
                        },
                        new
                        {
                            KommuneInfoID = 1134,
                            KommuneName = "Suldal"
                        },
                        new
                        {
                            KommuneInfoID = 1133,
                            KommuneName = "Hjelmeland"
                        },
                        new
                        {
                            KommuneInfoID = 1130,
                            KommuneName = "Strand"
                        },
                        new
                        {
                            KommuneInfoID = 1127,
                            KommuneName = "Randaberg"
                        },
                        new
                        {
                            KommuneInfoID = 1124,
                            KommuneName = "Sola"
                        },
                        new
                        {
                            KommuneInfoID = 1122,
                            KommuneName = "Gjesdal"
                        },
                        new
                        {
                            KommuneInfoID = 1121,
                            KommuneName = "Time"
                        },
                        new
                        {
                            KommuneInfoID = 1120,
                            KommuneName = "Klepp"
                        },
                        new
                        {
                            KommuneInfoID = 1119,
                            KommuneName = "Hå"
                        },
                        new
                        {
                            KommuneInfoID = 1114,
                            KommuneName = "Bjerkreim"
                        },
                        new
                        {
                            KommuneInfoID = 1112,
                            KommuneName = "Lund"
                        },
                        new
                        {
                            KommuneInfoID = 1111,
                            KommuneName = "Sokndal"
                        },
                        new
                        {
                            KommuneInfoID = 1108,
                            KommuneName = "Sandnes"
                        },
                        new
                        {
                            KommuneInfoID = 1106,
                            KommuneName = "Haugesund"
                        },
                        new
                        {
                            KommuneInfoID = 1103,
                            KommuneName = "Stavanger"
                        },
                        new
                        {
                            KommuneInfoID = 1101,
                            KommuneName = "Eigersund"
                        },
                        new
                        {
                            KommuneInfoID = 301,
                            KommuneName = "Oslo"
                        });
                });

            modelBuilder.Entity("Kartverket.Data.Status", b =>
                {
                    b.Property<int>("StatusNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatusNo"));

                    b.Property<string>("StatusName")
                        .HasColumnType("longtext");

                    b.HasKey("StatusNo");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusNo = 1,
                            StatusName = "Sendt"
                        },
                        new
                        {
                            StatusNo = 2,
                            StatusName = "Mottat"
                        },
                        new
                        {
                            StatusNo = 3,
                            StatusName = "Behandles"
                        },
                        new
                        {
                            StatusNo = 4,
                            StatusName = "Fullført"
                        },
                        new
                        {
                            StatusNo = 5,
                            StatusName = "Avvist"
                        });
                });

            modelBuilder.Entity("Kartverket.Data.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
